name: Lint
on: [push]
permissions:
  contents: read
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=3m
